### ISSUE TITLE
It doesn't compatible with Mac

### ISSUE THREAD

**Issue by Doublefire-Chen** [noah-herrington/spotify-lyrics-to-lrc#1]
At first, please let me thank you for your excellent project!
However, it didn't compatible with Mac. I have edited it for temporary use on Mac.
There are two reasons:

1. different file paths syntax in Win and Mac. eg: Win: C:\Users\Doublefire_Chen\lyric.txt   Mac: /Users/Doublefire_Chen/lyric.txt
2. different hot key in Win and Mac. eg: Win: Ctrl+C, Ctrl+V   Mac:Command+C, Command+V

By the way, there is no need to use module webbrowser to open the lyrics_url, using module requests maybe more efficient. And not using hotkey, just use program to get the txt from the url will also be helpful to the efficiency.
At last, don't worry. I already have solution to handle all problems mentioned above. I will help you to make this project more perfect and nice when I finished my mid-term exam. Damn it, I have to review my notes preparing for the mid-term exam right now. Bye~!
Good luck!

**Comment by tappyduckmancodes** [comment]
Oh my god, never thought someone would actually respond with issues! 

If you have the MacOS code, feel free to upload it as a pull request. 

If you could help with my code, that would be fantastic! My main issue right now is generating the headers for the link of the lyrics, as they change every reload of the Spotify Web Player page. If those could be generated (Requires Spotify V2 API token which I don't know how to get), it could be made fully automated (minus changes in filesystem for path)

**Comment by Doublefire-Chen** [comment]
I have finished my mid-term exam, now I can help you make it better. I will finish it as soon as possible.

**Comment by Doublefire-Chen** [comment]
I have made pull request, please check it my bro.

**Comment by tappyduckmancodes** [comment]
I've seen it, thank you so much!
I thought I responded to this email a while ago, my apologies.

I've tested it to be working, I'll approve the pull request right away.
You're truly great. Thank you for helping me with this.

One problem I've found is finding the Spotify V2 API token, it seems to
generate it on the first lyric request, allowing it to open the
https://spclient.wg.spotify.com/color-lyrics/v2/track/ file.
Would you know how to update it to generate it?

Thanks,
Me

**Comment by Doublefire-Chen** [comment]
>One problem I've found is finding the Spotify V2 API token, it seems to generate it on the first lyric request, allowing it to open the https://spclient.wg.spotify.com/color-lyrics/v2/track/ file. Would you know how to update it to generate it?

Hi, bro.
It is my pleasure to make this project better. However, I don't get your meaning. Could you please describe it more clearly?  In the process of my bag grabbing, I didn't find this API. Maybe a snapshot would be helpful.
Doublefire.Chen
